### ISSUE TITLE
game crash in or when leaving campfire room

### ISSUE THREAD

**Issue by jellybizzy** [ekunuke/vagante_issues#88] opened 2016-04-21 05:45 UTC
game just suddenly dissapears. no warning. usually right as im leaving the campfire room. sometimes while waiting in the campfire room.
ive had this happen in single player and in local co-op. at least 5 times. and spanning back a few months at least.
ive had this happen on my pc and at my buddies house.
seems to only happen in really long games.
no events shown in event viewer

my specs 
amd fx 8120
readeon r9 380
16gb ram
win 10 64bit
using xbox 360 wired controller.

screenshot just before it happened last.
![game crash](https://cloud.githubusercontent.com/assets/18588488/14698877/7fae31e0-0758-11e6-98c2-fffda8d0daa3.jpg)

log file changed to jpg to upload here.

![log](https://cloud.githubusercontent.com/assets/18588488/14699026/e99e889c-0759-11e6-87a2-3ba522ca16f4.jpg)

**Comment by k6l2** [comment] 2016-04-21 22:18
I've confirmed that these Act 4 crashes are due to changes in the generation code.  Specifically: 00:20:18.234 ERROR  : RoomDatabase::getRandomRoom - Found no rooms for Act 3, type: 8487
room type 8487 (wide shop rooms) are now allowed in generation, but none exist yet in the game causing it to crash.

**Comment by k6l2** [comment] 2016-04-21 22:27
The crash at least should be fixed in the next version, potentially allowing some levels in act 4 to generate without a shop (for now at least).

**Closed as completed by k6l2** 2016-04-21 22:27 UTC
